services:
  backend:
    image: gitlab.lan:5050/mbudit/gun-app-backend:latest
    container_name: gun_app_backend
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=192.168.50.96
      - DB_PORT=3306
      - DB_USER=budi
      - DB_PASS=shura130601
      - DB_NAME=linen_tracking
      - TRIGGER_SECRET=ksdhbvyiewbfiquofqebfkjq
      - PORT=5002
